# -----------------------------------------------------
# Core Settings
# Monitor, cursor, keyboard, layout, misc
# -----------------------------------------------------

# Monitor
source = ~/.config/hypr/conf/monitors/nwg-displays.conf

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

# Keyboard
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    numlock_by_default = true
    follow_mouse = 1
    mouse_refocus=false
    touchpad {
        natural_scroll = false
        scroll_factor = 1.0
        disable_while_typing = false
    }
    sensitivity = 0
}

# Layout
source = ~/.config/hypr/conf/layouts/default.conf

# Workspace rules
source = ~/.config/hypr/conf/workspaces/default.conf

# Misc
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    initial_workspace_tracking = 1
    on_focus_under_fullscreen = 1
    allow_session_lock_restore = true
}

# XWayland
xwayland {
    force_zero_scaling = true
}
