# -----------------------------------------------------
# Custom Configuration
# Add your personal Hyprland overrides here.
# This file is never overwritten by updates.
# -----------------------------------------------------

# Keyboard layout override
input {
    kb_layout = no
}

# Monitor scaling
monitor = ,preferred,auto,1.5
