#!/usr/bin/env bash
# archstoso.sh — ArchStoso automated Arch Linux installer entry point.
#
# This file is the TUI layer and phase orchestrator only.
# Disk operations:    lib/disk.sh → run_disk_setup
# Phase scripts:      scripts/1-setup.sh, 2-user.sh, 3-post-install.sh
# All configuration:  configs/setup.conf (written here, sourced by phase scripts)

set -euo pipefail

# ── Resolve the directory containing this script ───────────────────────────────
# BASH_SOURCE[0] is this file regardless of how the script was invoked or
# whether it was sourced. The readlink -f call resolves any symlinks so that
# relative paths derived from SCRIPT_DIR are always correct.
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

# ── Log file — exported so lib functions can reference it ─────────────────────
export INSTALL_LOG=/tmp/archstoso-install.log

# Tee stdout+stderr to the log file. The user sees everything in the terminal;
# the log file captures a full record for post-mortem if something fails.
exec > >(tee -a "$INSTALL_LOG") 2>&1

# ── Source libraries ──────────────────────────────────────────────────────────
# Order matters: validate.sh and disk.sh both call ui.sh functions, so ui.sh
# must be sourced first.
# shellcheck source=lib/ui.sh
source "$SCRIPT_DIR/lib/ui.sh"
# shellcheck source=lib/validate.sh
source "$SCRIPT_DIR/lib/validate.sh"
# shellcheck source=lib/disk.sh
source "$SCRIPT_DIR/lib/disk.sh"

# ── setup.conf helper ─────────────────────────────────────────────────────────
# Write or update a single KEY=VALUE line in setup.conf.
# If the key already exists it is replaced in-place; otherwise it is appended.
# Using delete-then-append (same approach as ArchTitus startup.sh) avoids the
# risk of sed in-place leaving a .bak file or failing on BSD-style sed.
set_option() {
    local key="$1"
    local value="$2"
    local conf="$SCRIPT_DIR/configs/setup.conf"

    # Strip any existing line for this key, then append the new value.
    if grep -q "^${key}=" "$conf" 2>/dev/null; then
        sed -i "/^${key}=/d" "$conf"
    fi
    echo "${key}=${value}" >> "$conf"
}

# ── Initialise an empty setup.conf ────────────────────────────────────────────
init_conf() {
    mkdir -p "$SCRIPT_DIR/configs"
    # Truncate to a header comment; set_option will append below it.
    printf '# ArchStoso installation configuration — generated by archstoso.sh\n' \
        > "$SCRIPT_DIR/configs/setup.conf"
}

# =============================================================================
# 1. Banner + environment checks
# =============================================================================

banner
run_environment_checks

# =============================================================================
# 2. Interactive prompts — collect all settings before any disk writes
# =============================================================================

section "Installation Settings"

init_conf

# ── a) Disk selection ─────────────────────────────────────────────────────────

info "Detecting available disks..."

# Capture list_disks output into an array, one element per disk line.
mapfile -t DISK_ENTRIES < <(list_disks)

if [[ "${#DISK_ENTRIES[@]}" -eq 0 ]]; then
    die "No disks detected. Cannot continue."
fi

echo
info "Select the target installation disk:"
echo

select_option DISK_ENTRY "${DISK_ENTRIES[@]}"
DISK="$(disk_path_from_entry "$DISK_ENTRY")"

echo
# Extract the display size from the entry for the confirmation prompt.
# Entry format: "/dev/nvme0n1  (953.9G — Micron ...)"
DISK_DISPLAY="${DISK_ENTRY}"

warn "Selected disk: ${DISK_DISPLAY}"
if ! confirm "This disk will be COMPLETELY ERASED. Continue?" n; then
    die "Disk selection aborted."
fi

set_option "DISK" "$DISK"

# ── b) Filesystem type ────────────────────────────────────────────────────────

echo
info "Select filesystem:"
echo

FS_OPTIONS=(
    "btrfs  (recommended — snapshots, compression)"
    "ext4   (simple, widely supported)"
)
select_option FS_ENTRY "${FS_OPTIONS[@]}"
# Extract just the first word: "btrfs" or "ext4".
FS_TYPE="${FS_ENTRY%% *}"

set_option "FS_TYPE" "$FS_TYPE"

# ── c) LUKS2 encryption ───────────────────────────────────────────────────────

echo
LUKS="no"
LUKS_PASSWORD=""

if confirm "Encrypt the root partition with LUKS2?" n; then
    LUKS="yes"
    ask_password LUKS_PASSWORD "Encryption passphrase"
fi

set_option "LUKS" "$LUKS"
# Store the password even when LUKS=no (empty string is safe).
set_option "LUKS_PASSWORD" "$LUKS_PASSWORD"

# ── d) Install type ───────────────────────────────────────────────────────────

echo
info "Select install type:"
echo

INSTALL_OPTIONS=(
    "HYPRLAND  (full desktop — Hyprland + ArchStoso dotfiles)"
    "BASE      (minimal system, no desktop environment)"
)
select_option INSTALL_ENTRY "${INSTALL_OPTIONS[@]}"
# Extract the first word: "HYPRLAND" or "BASE".
INSTALL_TYPE="${INSTALL_ENTRY%% *}"

set_option "INSTALL_TYPE" "$INSTALL_TYPE"

# ── e) Hostname ───────────────────────────────────────────────────────────────

echo
ask_validated HOSTNAME "Hostname" validate_hostname "archstoso"
set_option "HOSTNAME" "$HOSTNAME"

# ── f) Username ───────────────────────────────────────────────────────────────

echo
ask_validated USERNAME "Primary username" validate_username
set_option "USERNAME" "$USERNAME"

# ── g) User password ──────────────────────────────────────────────────────────

echo
ask_password USER_PASSWORD "Password for ${USERNAME}"
set_option "USER_PASSWORD" "$USER_PASSWORD"

# ── h) Root password ──────────────────────────────────────────────────────────

echo
ask_password ROOT_PASSWORD "Root password"
set_option "ROOT_PASSWORD" "$ROOT_PASSWORD"

# ── i) Timezone ───────────────────────────────────────────────────────────────

echo
info "Detecting timezone via GeoIP..."
DETECTED_TZ="$(detect_timezone)"
TIMEZONE=""

if [[ -n "$DETECTED_TZ" ]]; then
    info "Detected timezone: ${DETECTED_TZ}"
    if confirm "Use detected timezone: ${DETECTED_TZ}?" y; then
        TIMEZONE="$DETECTED_TZ"
    else
        ask_validated TIMEZONE "Timezone" validate_timezone
    fi
else
    warn "Could not detect timezone automatically."
    ask_validated TIMEZONE "Timezone" validate_timezone "Europe/Oslo"
fi

set_option "TIMEZONE" "$TIMEZONE"

# ── j) Keyboard layout ────────────────────────────────────────────────────────

echo
ask_validated KEYMAP "Console keymap" validate_keymap "no"
set_option "KEYMAP" "$KEYMAP"

# ── k) Dotfiles (HYPRLAND installs only) ─────────────────────────────────────

echo
INSTALL_DOTFILES="no"
DOTFILES_BRANCH=""

if [[ "$INSTALL_TYPE" == "HYPRLAND" ]]; then
    if confirm "Deploy ArchStoso dotfiles?" y; then
        INSTALL_DOTFILES="yes"
        ask DOTFILES_BRANCH "Dotfiles branch or tag" "main"
    fi
fi

set_option "INSTALL_DOTFILES" "$INSTALL_DOTFILES"
set_option "DOTFILES_BRANCH" "$DOTFILES_BRANCH"

# ── Locale — hardcoded, not prompted ─────────────────────────────────────────
LOCALE="en_US.UTF-8"
set_option "LOCALE" "$LOCALE"

ok "Configuration saved to configs/setup.conf"

# =============================================================================
# 3. Pre-flight summary
# =============================================================================

section "Ready to Install"

echo -e "  ${BOLD}Disk${RESET}            ${DISK_DISPLAY}"
echo -e "  ${BOLD}Filesystem${RESET}      ${FS_TYPE}"
if [[ "$LUKS" == "yes" ]]; then
    echo -e "  ${BOLD}Encryption${RESET}      LUKS2 — passphrase ${DIM}(set)${RESET}"
else
    echo -e "  ${BOLD}Encryption${RESET}      none"
fi
echo -e "  ${BOLD}Install type${RESET}    ${INSTALL_TYPE}"
echo -e "  ${BOLD}Hostname${RESET}        ${HOSTNAME}"
echo -e "  ${BOLD}Username${RESET}        ${USERNAME}"
echo -e "  ${BOLD}User password${RESET}   ${DIM}(set)${RESET}"
echo -e "  ${BOLD}Root password${RESET}   ${DIM}(set)${RESET}"
echo -e "  ${BOLD}Timezone${RESET}        ${TIMEZONE}"
echo -e "  ${BOLD}Keymap${RESET}          ${KEYMAP}"
if [[ "$INSTALL_TYPE" == "HYPRLAND" ]]; then
    if [[ "$INSTALL_DOTFILES" == "yes" ]]; then
        echo -e "  ${BOLD}Dotfiles${RESET}        yes — branch: ${DOTFILES_BRANCH}"
    else
        echo -e "  ${BOLD}Dotfiles${RESET}        no"
    fi
fi
echo -e "  ${BOLD}Locale${RESET}          ${LOCALE}"
echo

if ! confirm "Begin installation? This is the last chance to abort." n; then
    die "Installation aborted by user."
fi

# =============================================================================
# 4. Disk setup
# =============================================================================

section "Disk Setup"

# Re-source setup.conf so that all variables are exported for lib/disk.sh.
# shellcheck source=configs/setup.conf
source "$SCRIPT_DIR/configs/setup.conf"

# Export the vars that disk.sh reads from the environment.
export DISK FS_TYPE LUKS LUKS_PASSWORD

run_disk_setup

# Persist disk UUIDs so phase scripts can build the bootloader entry.
# disk.sh exports LUKS_UUID (outer partition) and ROOT_DEVICE after run_disk_setup.
if [[ "$LUKS" == "yes" ]]; then
    set_option "LUKS_UUID" "$LUKS_UUID"
fi
# ROOT_UUID is the filesystem UUID — blkid reads it from ROOT_DEVICE.
# For LUKS this is /dev/mapper/archroot; for plain installs it is PART_ROOT.
ROOT_UUID=$(blkid -s UUID -o value "$ROOT_DEVICE")
set_option "ROOT_UUID"  "$ROOT_UUID"
set_option "PART_ROOT"  "$PART_ROOT"

# =============================================================================
# 5. Pre-install: keyring, mirrors, pacstrap, fstab, zram
# =============================================================================

bash "$SCRIPT_DIR/scripts/0-preinstall.sh"

# =============================================================================
# 7. Copy installer into chroot, then run phase scripts
# =============================================================================

# Copy the entire installer tree into the new root before chrooting.
# Phase scripts source setup.conf from /root/archstoso-install/configs/.
cp -r "$SCRIPT_DIR" /mnt/root/archstoso-install

section "Phase 1: System Setup"
arch-chroot /mnt /root/archstoso-install/scripts/1-setup.sh

section "Phase 2: User Setup"
# Run as the target user so that home-directory paths resolve correctly.
# env -i gives a clean environment; sudo -u drops privileges for the script.
arch-chroot /mnt /usr/bin/env -i \
    HOME="/home/${USERNAME}" \
    USER="${USERNAME}" \
    LOGNAME="${USERNAME}" \
    sudo -u "${USERNAME}" \
    /root/archstoso-install/scripts/2-user.sh

section "Phase 3: Post-Install"
arch-chroot /mnt /root/archstoso-install/scripts/3-post-install.sh

# =============================================================================
# 8. Done
# =============================================================================

echo
echo -e "${DIM}$(printf '─%.0s' {1..72})${RESET}"
echo -e "${GREEN}${BOLD}  Installation complete!${RESET}"
echo -e "${DIM}$(printf '─%.0s' {1..72})${RESET}"
echo
echo -e "  ${WHITE}Remove the install media and reboot.${RESET}"
echo
echo -e "  ${DIM}Full install log: ${INSTALL_LOG}${RESET}"
echo
